name: Notify Python Client Repo

on:
  push:
    branches: ['**']
    tags: ['*.*.*']

jobs:
  notify-python-client:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch to evilflowers-protocol-python
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: EvilFlowersCatalog/evilflowers-protocol-python
          event-type: protocol-updated
          client-payload: '{"ref": "${{ github.ref_name }}"}'
